language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install coveralls flake8
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt
script:
    - flake8 versioncheck test
    - "py.test -n2 --cov=versioncheck --cov-config coverage.ini  --cov-report=xml --cov-report term --junit-xml=junit-result.xml test.py"
after_success:
    - coveralls
notifications:
    email:
        - tina.tang@emc.com